# Generated by Django 5.2 on 2025-10-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Номер счёта')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Банк')),
                ('bank_identification_number', models.CharField(max_length=50, verbose_name='БИК')),
            ],
            options={
                'verbose_name': 'Банковский счёт',
                'verbose_name_plural': 'Банковские счета',
                'ordering': ['bank_name'],
            },
        ),
    ]
