# Generated by Django 5.2 on 2025-12-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Корреспондентский счёт'),
        ),
    ]
