# Generated by Django 5.2 on 2025-12-20 15:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_correspondent_account'),
        ('customers', '0002_customer_account_customer_inn_customer_kpp'),
        ('organizations', '0002_organization_inn_organization_kpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('payment_kind', models.CharField(blank=True, max_length=20, verbose_name='Вид платежа')),
                ('payer_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН плательщика')),
                ('payer_kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП плательщика')),
                ('recipient_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН получателя')),
                ('recipient_kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП получателя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('amount_text', models.CharField(blank=True, max_length=255, verbose_name='Сумма прописью')),
                ('payment_purpose', models.TextField(verbose_name='Назначение платежа')),
                ('kbk', models.CharField(blank=True, max_length=50, verbose_name='КБК')),
                ('oktmo', models.CharField(blank=True, max_length=50, verbose_name='ОКТМО')),
                ('payment_operation_type', models.CharField(blank=True, default='01', max_length=4, verbose_name='Вид оп.')),
                ('payment_due_date', models.CharField(blank=True, max_length=20, verbose_name='Срок плат.')),
                ('payment_assignment_code', models.CharField(blank=True, max_length=20, verbose_name='Наз. пл.')),
                ('payment_priority', models.CharField(blank=True, default='5', max_length=5, verbose_name='Очеред. плат.')),
                ('payment_code', models.CharField(blank=True, default='0', max_length=5, verbose_name='Код')),
                ('reserve_field', models.CharField(blank=True, max_length=20, verbose_name='Рез. поле')),
                ('payment_basis', models.CharField(blank=True, max_length=50, verbose_name='Основание платежа')),
                ('tax_period', models.CharField(blank=True, max_length=50, verbose_name='Налоговый период')),
                ('doc_number', models.CharField(blank=True, max_length=50, verbose_name='Номер документа')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='organizations.organization', verbose_name='Плательщик')),
                ('payer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders_as_payer', to='accounts.account', verbose_name='Счёт плательщика')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='customers.customer', verbose_name='Получатель')),
                ('recipient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders_as_recipient', to='accounts.account', verbose_name='Счёт получателя')),
            ],
            options={
                'verbose_name': 'Платёжное поручение',
                'verbose_name_plural': 'Платёжные поручения',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
