# Generated by Django 5.2 on 2025-12-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
    ]
