# Generated by Django 5.2 on 2025-10-30 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('is_valid_until', models.DateField(verbose_name='Действителен до')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxies', to='customers.customer', verbose_name='Контрагент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxies', to='employees.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxies', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Доверенность',
                'verbose_name_plural': 'Доверенности',
                'ordering': ['-date_of_issue'],
            },
        ),
        migrations.CreateModel(
            name='ProxyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proxies.proxy', verbose_name='Доверенность')),
            ],
            options={
                'verbose_name': 'Элемент доверенности',
                'verbose_name_plural': 'Элементы доверенности',
                'ordering': ['id'],
            },
        ),
    ]
