# Generated by Django 5.2 on 2025-10-30 23:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActSpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('contract', models.CharField(blank=True, max_length=255, verbose_name='Договор')),
                ('invoice', models.CharField(blank=True, max_length=255, verbose_name='Счёт на оплату')),
                ('delivery_method', models.CharField(blank=True, max_length=255, verbose_name='Способ доставки')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Склад')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_acts', to='customers.customer', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Акт списания материальных ценностей',
                'verbose_name_plural': 'Акты списания материальных ценностей',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ActSpisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Сумма')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='act_spis.actspis', verbose_name='Акт списания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция акта списания',
                'verbose_name_plural': 'Позиции акта списания',
                'ordering': ['id'],
            },
        ),
    ]
