# Generated by Django 5.2 on 2025-10-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_spis', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actspisitem',
            options={'ordering': ['id'], 'verbose_name': 'Позиция акта списания материальных ценностей', 'verbose_name_plural': 'Позиции акта списания материальных ценностей'},
        ),
        migrations.RemoveField(
            model_name='actspis',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='actspis',
            name='invoice',
        ),
        migrations.AddField(
            model_name='actspis',
            name='commission_chairperson',
            field=models.CharField(blank=True, max_length=255, verbose_name='Председатель комиссии'),
        ),
        migrations.AddField(
            model_name='actspis',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_off_acts', to='employees.employee', verbose_name='Материально ответственное лицо'),
        ),
        migrations.AddField(
            model_name='actspisitem',
            name='unit_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='actspisitem',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='act_spis.actspis', verbose_name='Акт списания материальных ценностей'),
        ),
    ]
