# Generated by Django 5.2 on 2025-10-31 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_spis', '0002_alter_actspisitem_options_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actspis',
            name='commission_chairperson',
        ),
        migrations.RemoveField(
            model_name='actspis',
            name='responsible_employee',
        ),
        migrations.AddField(
            model_name='actspis',
            name='chairperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_off_acts', to='employees.employee', verbose_name='Председатель комиссии'),
        ),
    ]
