# Generated by Django 5.2 on 2025-12-20 19:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_account_customer_inn_customer_kpp'),
        ('organizations', '0002_organization_inn_organization_kpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Ставка НДС, %')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_acts', to='customers.customer', verbose_name='Заказчик')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_acts_as_executor', to='organizations.organization', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Акт выполненных работ',
                'verbose_name_plural': 'Акты выполненных работ',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceActLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='№')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование работы (услуги)')),
                ('unit', models.CharField(blank=True, default='шт.', max_length=32, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='service_acts.serviceact', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Строка акта',
                'verbose_name_plural': 'Строки акта',
                'ordering': ['order', 'id'],
            },
        ),
    ]
