# Generated by Django 5.2 on 2025-12-22 07:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_acts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceact',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='serviceactline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Ставка НДС, %'),
        ),
    ]
