# Generated by Django 5.2 on 2025-12-20 16:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_account_customer_inn_customer_kpp'),
        ('organizations', '0002_organization_inn_organization_kpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('period_from', models.DateField(verbose_name='Период с')),
                ('period_to', models.DateField(verbose_name='Период по')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_acts', to='customers.customer', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_acts', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Акт сверки',
                'verbose_name_plural': 'Акты сверки',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationActLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('document', models.CharField(blank=True, max_length=255, verbose_name='Документ')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Кредит')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reconciliation_acts.reconciliationact', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Строка акта сверки',
                'verbose_name_plural': 'Строки акта сверки',
                'ordering': ['order', 'date', 'id'],
            },
        ),
    ]
