# Generated by Django 5.2 on 2025-12-20 16:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_acts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationactline',
            name='customer_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Кредит контрагента'),
        ),
        migrations.AddField(
            model_name='reconciliationactline',
            name='customer_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Дебет контрагента'),
        ),
        migrations.AlterField(
            model_name='reconciliationactline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Кредит организации'),
        ),
        migrations.AlterField(
            model_name='reconciliationactline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Дебет организации'),
        ),
    ]
