# Generated by Django 5.2 on 2025-12-20 18:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_acts', '0002_reconciliationactline_customer_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationact',
            name='closing_balance_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо (контрагент)'),
        ),
        migrations.AddField(
            model_name='reconciliationact',
            name='opening_balance_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо (контрагент)'),
        ),
    ]
