# Generated by Django 5.2 on 2025-12-20 18:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_acts', '0003_reconciliationact_closing_balance_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationact',
            name='closing_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо (кредит орг.)'),
        ),
        migrations.AddField(
            model_name='reconciliationact',
            name='closing_credit_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо (кредит контр.)'),
        ),
        migrations.AddField(
            model_name='reconciliationact',
            name='closing_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо (дебет орг.)'),
        ),
        migrations.AddField(
            model_name='reconciliationact',
            name='closing_debit_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо (дебет контр.)'),
        ),
        migrations.AddField(
            model_name='reconciliationact',
            name='opening_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо (кредит орг.)'),
        ),
        migrations.AddField(
            model_name='reconciliationact',
            name='opening_credit_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо (кредит контр.)'),
        ),
        migrations.AddField(
            model_name='reconciliationact',
            name='opening_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо (дебет орг.)'),
        ),
        migrations.AddField(
            model_name='reconciliationact',
            name='opening_debit_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо (дебет контр.)'),
        ),
        migrations.AlterField(
            model_name='reconciliationact',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо (орг. итог)'),
        ),
        migrations.AlterField(
            model_name='reconciliationact',
            name='closing_balance_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо (контрагент итог)'),
        ),
        migrations.AlterField(
            model_name='reconciliationact',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо (орг. итог)'),
        ),
        migrations.AlterField(
            model_name='reconciliationact',
            name='opening_balance_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо (контрагент итог)'),
        ),
    ]
