# Generated by Django 5.2 on 2025-12-20 18:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_acts', '0004_reconciliationact_closing_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationact',
            name='closing_credit',
        ),
        migrations.RemoveField(
            model_name='reconciliationact',
            name='closing_credit_customer',
        ),
        migrations.RemoveField(
            model_name='reconciliationact',
            name='closing_debit',
        ),
        migrations.RemoveField(
            model_name='reconciliationact',
            name='closing_debit_customer',
        ),
        migrations.RemoveField(
            model_name='reconciliationact',
            name='opening_credit',
        ),
        migrations.RemoveField(
            model_name='reconciliationact',
            name='opening_credit_customer',
        ),
        migrations.RemoveField(
            model_name='reconciliationact',
            name='opening_debit',
        ),
        migrations.RemoveField(
            model_name='reconciliationact',
            name='opening_debit_customer',
        ),
        migrations.AlterField(
            model_name='reconciliationact',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо'),
        ),
        migrations.AlterField(
            model_name='reconciliationact',
            name='closing_balance_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Исходящее сальдо (контрагент)'),
        ),
        migrations.AlterField(
            model_name='reconciliationact',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо'),
        ),
        migrations.AlterField(
            model_name='reconciliationact',
            name='opening_balance_customer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Входящее сальдо (контрагент)'),
        ),
    ]
