# Generated by Django 5.2 on 2025-12-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_acts', '0005_remove_reconciliationact_closing_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconciliationact',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Акт сверки', 'verbose_name_plural': 'Акты сверки взаиморасчётов'},
        ),
    ]
